
'NOTE: DO NOT ADD REFERENCES TO COM.NETU.LIB HERE, INSTEAD ADD
'THE IMPORT ON THE REFERENCES OF THE PROJECT
Imports System.Runtime.InteropServices
Imports System.Collections.Generic
Imports System.Xml.Serialization
Imports System.Runtime.Serialization
Imports System.Data.Linq.Mapping
Imports System.ComponentModel.DataAnnotations

'<comments>
'************************************************************
' Temnplate: ModelBase2.visualBasic.txt
' Class autogenerated on 06-Sep-15 11:40:22 AM by ModelGenerator
' Extends base model object class
' *** DO NOT change code in this class.  
'     It will be re-generated and 
'     overwritten by the code generator ****
' Instead, change code in the extender class EmployeeRank
'
'************************************************************
'</comments>
Namespace VbBusObjects
<Table(Name := "EmployeeRank")><SelectObject("EmployeeRank")><KeyFieldName("RankId")> _
<DefaultMapperAttr(GetType(EmployeeRankDBMapper)), DataContract, _
ComVisible(False),Serializable(), System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)> _
partial class EmployeeRank
		Inherits ModelObject
		Implements IEquatable(Of EmployeeRank) 

#Region "Constructor"
    
    Friend sub New()
		Me.addValidator(New EmployeeRankRequiredFieldsValidator)
		Me.Id = ModelObjectKeyGen.nextId()
    End Sub

#End Region

#Region "Children and Parents"
	<OnDeserializing>
    Public sub OnDeserializingMethod(context as StreamingContext) 
		me.IsObjectLoading = true
    End Sub

	<OnDeserialized>
    Public sub OnDeserializedMethod( context as StreamingContext)

		me.IsObjectLoading = false
		me.isDirty = true
    End Sub

	Public Overrides sub loadObjectHierarchy()
		
	End Sub

	Public Overrides Function getChildren() As List(Of ModelObject) 
		Dim ret as New List(Of ModelObject)()
		
		return ret
	End Function
	
	Public Overrides Function getParents() As List(Of ModelObject)
		Dim ret as New List(Of ModelObject)()
		
		return ret
	End Function

#End Region
#Region "Field CONSTANTS"

			public Const STR_FLD_RANKID as String = "RankId"
			public Const STR_FLD_RANK as String = "Rank"


		public Const FLD_RANKID as Integer = 0
		public Const FLD_RANK as Integer = 1



        '''<summary>Returns the names of fields in the object as a string array.
        ''' Useful in automatically setting/getting values from UI objects (windows or web Form)</summary>
        ''' <returns> string array </returns>	 
        Public Overrides Function getFieldList() As String()
            Return New String() {STR_FLD_RANKID,STR_FLD_RANK}
        End Function
        
#END Region

#Region "Field Declarations"


	Private _RankId as System.Int64
	Private _Rank as System.String


#end Region

#Region "Field Properties"

	<Column(Name:="RankId",Storage:="_RankId", IsPrimaryKey:=True,DbType:="int NOT NULL",CanBeNull:=False )> _
<DataMember>	 Overridable Property PrRankId as System.Int64
	Get 
		return _RankId
	End Get 
	Set(ByVal value As System.Int64)
		if ModelObject.valueChanged(_RankId, value) then
			if me.IsObjectLoading = false then
				me.isDirty = true
				me.setFieldChanged(STR_FLD_RANKID)
			End If
			me._RankId = value

			me.raiseBroadcastIdChange()

		End if
	End Set 
	End Property 
	<Column(Name:="Rank",Storage:="_Rank", IsPrimaryKey:=False,DbType:="nvarchar NOT NULL",CanBeNull:=False )> _
<DataMember>	 Overridable Property PrRank as System.String
	Get 
		return _Rank
	End Get 
	Set(ByVal value As System.String)
		if ModelObject.valueChanged(_Rank, value) then
		if value isNot Nothing andAlso value.Length > 50 Then
			Throw new ModelObjectFieldTooLongException("Rank")
		End If
			if me.IsObjectLoading = false then
				me.isDirty = true
				me.setFieldChanged(STR_FLD_RANK)
			End If
			me._Rank = value

		End if
	End Set 
	End Property 

#End Region

#Region "Getters/Setters of values by field index / name"
    Public Overloads Overrides Function getAttribute(ByVal fieldKey As Integer) As Object
		

		select case fieldKey
		case FLD_RANKID
			return me.PrRankId
		case FLD_RANK
			return me.PrRank
		case else
			return nothing
		end select


    End Function

    Public Overloads Overrides Function getAttribute(ByVal fieldKey As String) As Object
		fieldKey = fieldKey.ToLower

		if fieldKey=STR_FLD_RANKID.ToLower() Then
			return me.PrRankId
		else if fieldKey=STR_FLD_RANK.ToLower() Then
			return me.PrRank
		else
			return nothing
		end If
    End Function

    Public Overloads Overrides Sub setAttribute(ByVal fieldKey As Integer, ByVal val As Object)
		Try
		Select Case fieldKey
		case FLD_RANKID
			If Val Is DBNull.Value OrElse Val Is Nothing Then
				Me.PrRankId = Nothing
			Else
				Me.PrRankId=CType(val,System.Int64)
			End If
			return
		case FLD_RANK
			If Val Is DBNull.Value OrElse Val Is Nothing Then
				Me.PrRank = Nothing
			Else
				Me.PrRank=CType(val,System.String)
			End If
			return
		case else
			return
		end select

		Catch ex As Exception
			Throw New ApplicationException(String.Format("Error setting field with index {0}, value ""{1}"" : {2}", fieldKey, val, ex.Message))
		End Try
    End Sub

    Public Overloads Overrides Sub setAttribute(ByVal fieldKey As String, ByVal val As Object)
		
		fieldKey = fieldKey.ToLower
		Try
		if  fieldKey=STR_FLD_RANKID.ToLower() Then
			If Val Is DBNull.Value OrElse Val Is Nothing Then
				Me.PrRankId = Nothing
			Else
				Me.PrRankId=Convert.ToInt64(val)
			End If
			return
		else if  fieldKey=STR_FLD_RANK.ToLower() Then
			If Val Is DBNull.Value OrElse Val Is Nothing Then
				Me.PrRank = Nothing
			Else
				Me.PrRank=Convert.ToString(val)
			End If
			return
		end If
		Catch ex As Exception
			Throw New ApplicationException(String.Format("Error setting field with index {0}, value ""{1}"" : {2}", fieldKey, val, ex.Message))
		End Try

    End Sub

#End Region
#Region "Overrides of GetHashCode, Equals "
	Public Overloads Function Equals(ByVal other As EmployeeRank) As Boolean _     
		Implements System.IEquatable(Of EmployeeRank).Equals       
		
			'typesafe equals, checks for equality of fields
			If other Is Nothing Then Return False       
			If other Is Me Then Return True
		
			Return me.PrRankId= other.PrRankId _
				AndAlso me.PrRank= other.PrRank
				
	End Function
	
	Public Overrides Function GetHashCode() As Integer
        'using Xor has the advantage of not overflowing the integer.
        Return me.PrRankId.GetHashCode _
				Xor me.getStringHashCode(Me.PrRank) 
    
    End Function
    
    Public Overloads Overrides Function Equals(ByVal Obj As Object) As Boolean
		
		Dim temp = TryCast(obj, EmployeeRank)       
		If temp IsNot Nothing Then 
			Return Me.Equals(temp)
		Else
			Return False
		End If

    End Function
	
	Public Shared Operator =(ByVal obj1 As EmployeeRank, ByVal obj2 As EmployeeRank) As Boolean       
		Return Object.Equals(obj1 ,obj2)    
	End Operator    
	
	Public Shared Operator <>(ByVal obj1 As EmployeeRank, ByVal obj2 As EmployeeRank) As Boolean       
		Return Not (obj1 = obj2)    
	End Operator

#End Region

#Region "Copy and sort"

	Public Overrides Function copy() as IModelObject
		'creates a shallow copy
        Dim ret as EmployeeRank =  new EmployeeRank()
		ret.PrRankId = me.PrRankId
		ret.PrRank = me.PrRank
		
		return ret
		
	End Function
	
#End Region



#Region "ID Property"
	
    <DataMember>Public NotOverridable Overrides Property Id() As object
        Get
            return me._RankId
        End Get
        Set(ByVal value As object)
             me._RankId = Clng(value)
             me.raiseBroadcastIdChange()
        End Set
    End Property
#End Region
	
#Region "Extra Code"
	
#End Region
	
	End Class

#Region "Req Fields validator"
	<System.Runtime.InteropServices.ComVisible(False)> _
    Public Class EmployeeRankRequiredFieldsValidator
        Implements IModelObjectValidator

        Public Sub validate(ByVal imo As org.model.lib.Model.IModelObject) _
                    Implements org.model.lib.IModelObjectValidator.validate

            Dim mo As EmployeeRank = CType(imo, EmployeeRank)
			if String.isNullOrEmpty( mo.PrRank) Then
		Throw new ModelObjectRequiredFieldException("Rank")
End if 

			
        End Sub

    End Class
#End Region

End Namespace

