using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Data.Linq.Mapping;

//<comments>
//************************************************************
// Template: ModelBaseExtender2.csharp.txt
// Class autogenerated on 16-Jun-15 4:19:00 PM by ModelGenerator
// Extends base model object class
// *** FELL FREE to change code in this class.  
//     It will NOT be re-generated and 
//     overwritten by the code generator ****
// 
//************************************************************
//</comments>

namespace OracleModel {

	public class RegionFactory {

		//Shared function to create a new instance of the class and return it.
		//you can create other shared functions to return a new 
		//instance with parameters
		public static Region Create() {
			return new Region();
		}

	}

	public partial class Region  {

		#region "Custom Methods "

		#endregion

	}

}

