using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using org.model.lib;
using org.model.lib.Model;
using org.model.lib.db;

using System.Linq;
using CsModelObjects;
using System.Data.Linq.Mapping;

//<comments>
// Template: DBMapperBase.csharp.txt
//************************************************************
// 
// Class autogenerated on11/07/2015 12:52:19 PM by ModelGenerator
// Extends base DBMapperBase object class
// *** DO NOT change code in this class.  
//     It will be re-generated and 
//     overwritten by the code generator ****
// Instead, change code in the extender class AccountDBMapper
//
//************************************************************
//</comments>

namespace CsModelMappers {

	[System.Runtime.InteropServices.ComVisible(false)]
	[Table(Name = "Account")]
	[SelectObject("Account")][KeyFieldName("accountid")]
	public class AccountDBMapper : DBMapper {

		#region "Constructors "
		public AccountDBMapper(DBUtils _dbConn) : base(_dbConn) {
		}


		public AccountDBMapper() : base() {
		}
		#endregion

		#region "Overloaded Functions"

		public new Account findWhere(string sWhereClause, params object[] @params) {

			return (Account)base.findWhere(sWhereClause, @params);
		}


		public void saveAccount(Account mo) {
			base.save(mo);
		}

		public new Account findByKey(object keyval) {

			return (Account)base.findByKey(keyval);

		}

		#endregion


		#region "getUpdateDBCommand"
		public override IDbCommand getUpdateDBCommand(IModelObject modelObj, string sql) {
			Account obj = (Account)modelObj;
			IDbCommand stmt = this.dbConn.getCommand(sql);
			stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_ACCOUNT,obj.PrAccount));
			stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_ACCOUNTTYPEID,obj.PrAccountTypeid));
			stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_BANKACCNUMBER,obj.PrBankaccnumber));
			stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_NEXTCHECKNUMBER,obj.PrNextCheckNumber));
			stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_DESCRIPTION,obj.PrDescription));
			stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_CREATEDATE,obj.CreateDate));
			stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_UPDATEDATE,obj.UpdateDate));
			stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_UPDATEUSER,obj.UpdateUser));
			stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_CREATEUSER,obj.CreateUser));

			if (obj.isNew){
			} else {
			//only add primary key if we are updating and as the last parameter
				stmt.Parameters.Add(this.dbConn.getParameter(Account.STR_FLD_ACCOUNTID,obj.PrAccountid));
			}

			return stmt;
		}
		#endregion
#region "Save Children Code"
	public override void saveChildren(IModelObject mo) {

		Account ret = (Account)mo;
		//*Child Association:bankaccountinfo
		if (ret.BankAccountInfoLoaded) { //scc 
			CsModelMappers.AccountBankInfoDBMapper bankaccountinfoMapper = new CsModelMappers.AccountBankInfoDBMapper(this.dbConn);
			bankaccountinfoMapper.save(ret.PrBankAccountInfo);
		}
	}
#endregion



		#region "Find functions"

		///	<summary>Given an sql statement, it opens a result set, and for each record returned, 
		///	it creates and loads a ModelObject. 
		/// </summary>
		///	<param name="sWhereClause">where clause to be applied to "selectall" statement 
		/// that returns one or more records from the database, corresponding to the ModelObject we are going to load </param>
		///	<param name="params"> Parameter values to be passed to sql statement </param>
		///	<returns> A List(Of Account) object containing all objects loaded </returns>
		///	 
		public new List<Account> findList(string sWhereClause, params object[] @params) {

			string sql = this.getSqlWithWhereClause(sWhereClause);
			IDataReader rs = null;
			List<Account> molist = new List<Account>();

			try {
				rs = dbConn.getDataReaderWithParams(sql, @params);
				this.Loader.DataSource = rs;

				while (rs.Read()) {
					IModelObject mo = this.getModelInstance();
					this.Loader.load(mo);
					molist.Add((Account)mo);

				}


			} finally {
				this.dbConn.closeDataReader(rs);
			}

			return molist;

		}

		///	<summary>Given an sql statement, it opens a result set, and for each record returned, 
		///	it creates and loads a ModelObject. </summary>
		///	<param name="sWhereClause">where clause to be applied to "selectall" statement 
		/// that returns one or more records from the database, corresponding to the ModelObject we are going to load </param>
		///	<param name="params"> List of IDataParameters to be passed to sql statement </param>
		///	<returns> A List(Of Account) object containing all objects loaded </returns>
		///	 
		public List<Account> findList(string sWhereClause, List<IDataParameter> @params) {

			string sql = this.getSqlWithWhereClause(sWhereClause);
			IDataReader rs = null;
			List<Account> molist = new List<Account>();

			try {
				rs = dbConn.getDataReader(sql, @params);
				this.Loader.DataSource = rs;

				while (rs.Read()) {
					IModelObject mo = this.getModelInstance();
					this.Loader.load(mo);
					molist.Add((Account)mo);

				}


			} finally {
				this.dbConn.closeDataReader(rs);
			}

			return molist;

		}


		///    
		///	 <summary>Returns all records from database for a coresponding ModelObject </summary>
		/// <returns>List(Of Account) </returns>
		public List<Account> findAll()
		{
			return this.findList(string.Empty);
		}

		public override IModelObjectLoader Loader {
			get {
				if (this._loader == null) {
					this._loader = new AccountDataReaderLoader();
				}
				return this._loader;
			}
			set { this._loader = value; }
		}

		#endregion

		public override IModelObject getModelInstance() {
			return new Account();
		}

	}

	#region " Account Loader "
	[System.Runtime.InteropServices.ComVisible(false)]
	public class AccountDataReaderLoader : DataReaderLoader {
		public override void load(IModelObject mo) {
			const int DATAREADER_FLD_ACCOUNTID = 0;
			const int DATAREADER_FLD_ACCOUNT = 1;
			const int DATAREADER_FLD_ACCOUNTTYPEID = 2;
			const int DATAREADER_FLD_BANKACCNUMBER = 3;
			const int DATAREADER_FLD_NEXTCHECKNUMBER = 4;
			const int DATAREADER_FLD_DESCRIPTION = 5;
			const int DATAREADER_FLD_CREATEDATE = 6;
			const int DATAREADER_FLD_UPDATEDATE = 7;
			const int DATAREADER_FLD_UPDATEUSER = 8;
			const int DATAREADER_FLD_CREATEUSER = 9;

			Account obj = (Account)mo;
			obj.IsObjectLoading = true;

			if (!this.reader.IsDBNull(DATAREADER_FLD_ACCOUNTID) ) {
				obj.PrAccountid = Convert.ToInt64(this.reader.GetInt32(DATAREADER_FLD_ACCOUNTID));
			}
			if (!this.reader.IsDBNull(DATAREADER_FLD_ACCOUNT) ) {
				obj.PrAccount = this.reader.GetString(DATAREADER_FLD_ACCOUNT);
			}
			if (!this.reader.IsDBNull(DATAREADER_FLD_ACCOUNTTYPEID) ) {
				obj.PrAccountTypeid = Convert.ToInt64(this.reader.GetInt32(DATAREADER_FLD_ACCOUNTTYPEID));
			}
			if (!this.reader.IsDBNull(DATAREADER_FLD_BANKACCNUMBER) ) {
				obj.PrBankaccnumber = this.reader.GetString(DATAREADER_FLD_BANKACCNUMBER);
			}
			if (!this.reader.IsDBNull(DATAREADER_FLD_NEXTCHECKNUMBER) ) {
				obj.PrNextCheckNumber = this.reader.GetString(DATAREADER_FLD_NEXTCHECKNUMBER);
			}
			if (!this.reader.IsDBNull(DATAREADER_FLD_DESCRIPTION) ) {
				obj.PrDescription = this.reader.GetString(DATAREADER_FLD_DESCRIPTION);
			}
			if (!this.reader.IsDBNull(DATAREADER_FLD_CREATEDATE) ) {
				obj.CreateDate = this.reader.GetDateTime(DATAREADER_FLD_CREATEDATE);
			}
			if (!this.reader.IsDBNull(DATAREADER_FLD_UPDATEDATE) ) {
				obj.UpdateDate = this.reader.GetDateTime(DATAREADER_FLD_UPDATEDATE);
			}
			if (!this.reader.IsDBNull(DATAREADER_FLD_UPDATEUSER) ) {
				obj.UpdateUser = this.reader.GetString(DATAREADER_FLD_UPDATEUSER);
			}
			if (!this.reader.IsDBNull(DATAREADER_FLD_CREATEUSER) ) {
				obj.CreateUser = this.reader.GetString(DATAREADER_FLD_CREATEUSER);
			}


			obj.isNew = false;
			// since we've just loaded from database, we mark as "old"
			obj.isDirty = false;
			obj.IsObjectLoading = false;
			obj.afterLoad();

			return;

		}

	}

	#endregion

	///<summary>
	/// Final Class with convinience shared methods for loading/saving the AccountRank ModelObject. 
	///</summary>
	[System.Runtime.InteropServices.ComVisible(false)]
	public sealed class AccountDataUtils {

		#region "Shared ""get"" Functions "

		public static List<Account> findList(string @where, params object[] @params) {

			AccountDBMapper dbm = new AccountDBMapper();
			return dbm.findList(@where, @params);

		}

		public static List<Account> findList(string @where, List<IDataParameter> listOfIParams) {

			AccountDBMapper dbm = new AccountDBMapper();
			return dbm.findList(@where,listOfIParams);

		}

		public static Account findOne(string @where, params object[] @params) {

			AccountDBMapper dbm = new AccountDBMapper();
			return (Account)dbm.findWhere(@where, @params);

		}

		public static List<Account> findList(){

			return new AccountDBMapper().findAll();

		}

		public static Account findByKey(object id) {

			return (Account)new AccountDBMapper().findByKey(id);

		}

		/// <summary>
		/// Reload the Account from the database
		/// </summary>
		/// <remarks>
		/// use this method when you want to relad the Account 
		/// from the database, discarding any changes
		/// </remarks>
		public static void reload(ref Account mo) {

			if (mo == null) {
				throw new System.ArgumentNullException("null object past to reload function");
			}

			mo = (Account)new AccountDBMapper().findByKey(mo.Id);

		}

		#endregion

		#region "Shared Save and Delete Functions"
		/// <summary>
		/// Convinience method to save a Account Object.
		/// Important note: DO NOT CALL THIS IN A LOOP!
		/// </summary>
		/// <param name="AccountObj"></param>
		/// <remarks>
		/// Important note: DO NOT CALL THIS IN A LOOP!  
		/// This method simply instantiates a AccountDBMapper and calls the save method
		/// </remarks>
		public static void saveAccount(params Account[] AccountObj)
		{

			AccountDBMapper dbm = new AccountDBMapper();
			dbm.saveList(AccountObj.ToList());


		}


		public static void deleteAccount(Account AccountObj)
		{

			AccountDBMapper dbm = new AccountDBMapper();
			dbm.delete(AccountObj);

		}
		#endregion

		#region "Data Table and data row load/save "

		public static void saveAccount(DataRow dr, ref Account mo) {
			if (mo == null) {
				mo = new Account();
			}

			foreach (DataColumn dc in dr.Table.Columns) {
				mo.setAttribute(dc.ColumnName, dr[dc.ColumnName]);
			}

			saveAccount(mo);

		}

		public static void saveAccount(DataTable dt, ref Account mo) {
			foreach (DataRow dr in dt.Rows) {
				saveAccount(dr, ref mo);
			}

		}

		public static Account loadFromDataRow(DataRow r) {

			DataRowLoader a = new DataRowLoader();
			IModelObject mo = new Account();
			a.DataSource = r;
			a.load(mo);
			return (Account)mo;

		}

		#endregion

	}

}


