'NOTE: DO NOT ADD REFERENCES TO COM.NETU.LIB HERE, INSTEAD ADD
'THE IMPORT ON THE REFERENCES OF THE PROJECT

Imports System.Data.Linq.Mapping

'<comments>
'Template: DBMapperBase.visualBasic.txt
'************************************************************
' Class autogenerated on 09/01/2017 22:36:20 by ModelGenerator
' Extends base DBMapperBase object class
' *** DO NOT change code in this class.  
'     It will be re-generated and 
'     overwritten by the code generator ****
' Instead, change code in the extender class TestTableNoIncrementDBMapper
'
'************************************************************
'</comments>
''
Namespace VbBusObjects.DBMappers
	<System.Runtime.InteropServices.ComVisible(False)>
	<Table(Name := "TestTableNoIncrement")> _
		<AttrIsPrimaryKeyAutogenerated(False)><SelectObject("TestTableNoIncrement")><KeyFieldName("TestTableNoIncrementId")> _
    public Class TestTableNoIncrementDBMapper
        Inherits DBMapper
		
#Region "Constructors "
    Public Sub New(ByVal _dbConn As DBUtils)
        MyBase.new(_dbConn)
    End Sub
        
        
    Public Sub New()
        MyBase.new()
    End Sub
#End Region

#Region "Overloaded Functions"
		
	Public Shadows Function findWhere(ByVal sWhereClause As String, _
                                        ByVal ParamArray params() As Object)  As TestTableNoIncrement
		
        return DirectCast(MyBase.findWhere(sWhereClause, params), TestTableNoIncrement)
    End Function
        

	Public Sub saveTestTableNoIncrement(ByVal mo As TestTableNoIncrement)
        MyBase.save(mo)
    End Sub
        
    Public Shadows Function findByKey(ByVal keyval As object) As TestTableNoIncrement

        Return DirectCast(MyBase.findByKey(keyval), TestTableNoIncrement)

    End Function
        
#End Region

#Region "getUpdateDBCommand"
        Public Overrides Function getUpdateDBCommand(ByVal modelObj As IModelObject, ByVal sql As String) As IDbCommand

             Dim p As IDataParameter = Nothing
             Dim obj as TestTableNoIncrement = DirectCast(modelObj,TestTableNoIncrement)
             Dim stmt As IDbCommand = Me.dbConn.getCommand(sql)
			stmt.Parameters.Add(Me.dbConn.getParameter(TestTableNoIncrement.STR_FLD_TESTTABLENOINCREMENT,obj.PrTestTableNoIncrement))
			stmt.Parameters.Add(Me.dbConn.getParameter(TestTableNoIncrement.STR_FLD_CREATEDATE,obj.CreateDate))
			stmt.Parameters.Add(Me.dbConn.getParameter(TestTableNoIncrement.STR_FLD_UPDATEDATE,obj.UpdateDate))
			stmt.Parameters.Add(Me.dbConn.getParameter(TestTableNoIncrement.STR_FLD_UPDATEUSER,obj.UpdateUser))
			stmt.Parameters.Add(Me.dbConn.getParameter(TestTableNoIncrement.STR_FLD_CREATEUSER,obj.CreateUser))

			stmt.Parameters.Add(Me.dbConn.getParameter(TestTableNoIncrement.STR_FLD_TESTTABLENOINCREMENTID,obj.PrTestTableNoIncrementId))


             return stmt

        End Function

#End Region

#Region "Find functions"

	'''	<summary>Given an sql statement, it opens a result set, and for each record returned, it creates and loads a ModelObject. </summary>
	'''	<param name="sWhereClause">where clause to be applied to "selectall" statement 
	''' that returns one or more records from the database, corresponding to the ModelObject we are going to load </param>
	'''	<param name="params"> Parameter values to be passed to sql statement </param>
	'''	<returns> A List(Of TestTableNoIncrement) object containing all objects loaded </returns>
	'''	 
	Public shadows Function findList(ByVal sWhereClause As String, _
										ByVal ParamArray params() As Object) _
										As List(Of TestTableNoIncrement)

		dim sql as String = Me.getSqlWithWhereClause(sWhereClause)
		Dim rs As IDataReader = Nothing
		Dim molist As New List(Of TestTableNoIncrement)
						
		Try				
			rs = dbConn.getDataReaderWithParams(sql, params)
            Me.Loader.DataSource = rs
               
			Do While rs.Read
				Dim mo As IModelObject = Me.getModelInstance
				Me.Loader.load(mo)
                molist.Add(DirectCast(mo, TestTableNoIncrement))
					
			Loop

				
		Finally
			Me.dbConn.closeDataReader(rs)
		End Try

		Return molist

	End Function
    
	Public Shadows Function findList(ByVal sWhereClause As String, _
        ByVal params As List(Of IDataParameter)) _
        As List(Of TestTableNoIncrement)

        Dim sql As String = Me.getSqlWithWhereClause(sWhereClause)
        Dim rs As IDataReader = Nothing
        Dim molist As New List(Of TestTableNoIncrement)

        Try
            rs = dbConn.getDataReader(sql, params)
            Me.Loader.DataSource = rs

            Do While rs.Read
                Dim mo As IModelObject = Me.getModelInstance
                Me.Loader.load(mo)
                molist.Add(DirectCast(mo, TestTableNoIncrement))

            Loop


        Finally
            Me.dbConn.closeDataReader(rs)
        End Try

        Return molist

    End Function

	'''    
	'''	 <summary>Returns all records from database for a coresponding ModelObject </summary>
	''' <returns>List(Of TestTableNoIncrement) </returns>
	Public Function findAll() As List(Of TestTableNoIncrement)
		Return Me.findList(String.Empty)
	End Function
		
	public Overrides Property Loader() As IModelObjectLoader
		Get
			if me._loader is Nothing then 
				me._loader = New TestTableNoIncrementDataReaderLoader
			end If
			return me._loader
        End Get
        Set(value as IModelObjectLoader)
			me._loader = value
        end Set
    End Property

#End Region
		
	Public Overrides Function getModelInstance() As IModelObject
		return new TestTableNoIncrement()
    End Function
		
End Class

#Region " TestTableNoIncrement Loader "
	<System.Runtime.InteropServices.ComVisible(False)> _
	Public Class TestTableNoIncrementDataReaderLoader
		Inherits DataReaderLoader

			Public Overrides sub load(ByVal mo As IModelObject)

			Const DATAREADER_FLD_TESTTABLENOINCREMENTID as Integer = 0
			Const DATAREADER_FLD_TESTTABLENOINCREMENT as Integer = 1
			Const DATAREADER_FLD_CREATEDATE as Integer = 2
			Const DATAREADER_FLD_UPDATEDATE as Integer = 3
			Const DATAREADER_FLD_UPDATEUSER as Integer = 4
			Const DATAREADER_FLD_CREATEUSER as Integer = 5

			
            Dim obj As TestTableNoIncrement = directCast(mo, TestTableNoIncrement)
            obj.IsObjectLoading = True

			if me.reader.IsDBNull(DATAREADER_FLD_TESTTABLENOINCREMENTID) = false Then
				obj.PrTestTableNoIncrementId = Convert.ToInt64(me.reader.GetInt32(DATAREADER_FLD_TESTTABLENOINCREMENTID))
			End if
			if me.reader.IsDBNull(DATAREADER_FLD_TESTTABLENOINCREMENT) = false Then
				obj.PrTestTableNoIncrement = me.reader.GetString(DATAREADER_FLD_TESTTABLENOINCREMENT)
			End if
			if me.reader.IsDBNull(DATAREADER_FLD_CREATEDATE) = false Then
				obj.CreateDate = me.reader.GetDateTime(DATAREADER_FLD_CREATEDATE)
			End if
			if me.reader.IsDBNull(DATAREADER_FLD_UPDATEDATE) = false Then
				obj.UpdateDate = me.reader.GetDateTime(DATAREADER_FLD_UPDATEDATE)
			End if
			if me.reader.IsDBNull(DATAREADER_FLD_UPDATEUSER) = false Then
				obj.UpdateUser = me.reader.GetString(DATAREADER_FLD_UPDATEUSER)
			End if
			if me.reader.IsDBNull(DATAREADER_FLD_CREATEUSER) = false Then
				obj.CreateUser = me.reader.GetString(DATAREADER_FLD_CREATEUSER)
			End if

            
            obj.isNew = false ' since we've just loaded from database, we mark as "old"
            obj.isDirty = False
			obj.IsObjectLoading = False
			obj.afterLoad()

            return
            
        End sub
	
	End Class

#End Region
		
	'''<summary>
    ''' Final Class with convinience shared methods for loading/saving the EmployeeRank ModelObject. 
    '''</summary>
	<System.Runtime.InteropServices.ComVisible(False)> _
	Public NotInheritable Class TestTableNoIncrementDataUtils

#Region "Shared ""get"" Functions "

		Public Shared Function findList(ByVal where As String, ByVal ParamArray params() As Object) _
					As List(Of TestTableNoIncrement)

            dim dbm as TestTableNoIncrementDBMapper = new TestTableNoIncrementDBMapper()
            Return dbm.findList(where, params)

        End Function
		
		Public Shared Function findList(ByVal where As String, ByVal params As List(Of IDataParameter)) _
										As List(Of TestTableNoIncrement)

            Dim dbm As TestTableNoIncrementDBMapper = New TestTableNoIncrementDBMapper()
            Return dbm.findList(where, params)

        End Function

		Public Shared Function findOne(ByVal where As String, ByVal ParamArray params() As Object) _
					As TestTableNoIncrement

            Dim dbm As TestTableNoIncrementDBMapper = New TestTableNoIncrementDBMapper()
            Return DirectCast(dbm.findWhere(where, params), TestTableNoIncrement)

        End Function
        
        
         Public Shared Function findList() As List(Of TestTableNoIncrement)
			
			return new TestTableNoIncrementDBMapper().findAll()
			
        End Function
        
        Public Shared Function findByKey(id as object) as TestTableNoIncrement
			
			return DirectCast( new TestTableNoIncrementDBMapper().findByKey(id),TestTableNoIncrement)
                        
        end function
        
		''' <summary>
        ''' Reload the TestTableNoIncrement from the database
        ''' </summary>
        ''' <remarks>
		''' use this method when you want to relad the TestTableNoIncrement 
		''' from the database, discarding any changes
		''' </remarks>
		Public Shared Sub reload(ByRef mo As TestTableNoIncrement)
			
			If mo Is Nothing Then
                Throw New System.ArgumentNullException("null object past to reload function")
            End If
            
			mo = DirectCast(New TestTableNoIncrementDBMapper().findByKey(mo.Id), TestTableNoIncrement)
            
        End Sub

#End Region

#Region "Shared Save and Delete Functions"
		''' <summary>
        ''' Convinience method to save a TestTableNoIncrement Object.
        ''' Important note: DO NOT CALL THIS IN A LOOP!
        ''' </summary>
        ''' <param name="TestTableNoIncrementObj"></param>
        ''' <remarks>
		''' Important note: DO NOT CALL THIS IN A LOOP!  
		''' This method simply instantiates a TestTableNoIncrementDBMapper and calls the save method
		''' </remarks>
		public shared sub saveTestTableNoIncrement(ByVal ParamArray TestTableNoIncrementObj() As TestTableNoIncrement)
            
            dim dbm as TestTableNoIncrementDBMapper = new TestTableNoIncrementDBMapper()
            dbm.saveList(TestTableNoIncrementObj.ToList)

                       
       end sub
       

       public shared sub deleteTestTableNoIncrement(ByVal TestTableNoIncrementObj As TestTableNoIncrement)
            
            dim dbm as TestTableNoIncrementDBMapper = new TestTableNoIncrementDBMapper()
            dbm.delete(TestTableNoIncrementObj)
            
        end sub
#End Region

#Region "Data Table and data row load/save "        
        Public Shared Sub saveTestTableNoIncrement(ByVal dr As DataRow, _
                                                 Optional ByRef mo As TestTableNoIncrement = Nothing)

            if mo is Nothing then 
				mo = new TestTableNoIncrement()
			end if
			
            For Each dc As DataColumn In dr.Table.Columns
                mo.setAttribute(dc.ColumnName, dr.Item(dc.ColumnName))
            Next

            call saveTestTableNoIncrement(mo)

        End Sub
        
         
        Public Shared Sub saveTestTableNoIncrement(ByVal dt As DataTable, _
                                                 Optional ByRef mo As TestTableNoIncrement = Nothing)

            For Each dr As DataRow In dt.Rows
            	call saveTestTableNoIncrement(dr,mo)
            Next
			
        End Sub
        
		 Public Shared Function loadFromDataRow(ByVal r As DataRow) As TestTableNoIncrement

            Dim a As New DataRowLoader
            Dim mo As IModelObject = new TestTableNoIncrement()
            a.DataSource = r
            a.load(mo)
            Return DirectCast(mo, TestTableNoIncrement)

        End Function

#End Region

    End Class
	
End Namespace

